// Image pools — Cloudinary (real project photos)
const GOLF = [
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671321/kigl4adzgrqyrwdfcg7o.png',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671334/woa4p1d1zugjvfhtxpfo.png',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671336/hpuiix8xfu0x9dwjpcpu.png',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671353/jqzqequqowm0av78uoxp.png',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671355/lwbz08ntbsxvkyzcq9r3.png',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671371/ez6nkz05anbplaxpfd4l.png',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671374/cguuahtupjkayczqwtj0.png',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671375/vel7c6duqzy1p16kakml.jpg',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671386/ijyrbb2gdo6z921labzv.jpg',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671388/kyqefehpgzsbbyyrzdhj.jpg',
];
const RESORT = [
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671447/dq8l14ajn2y7kxdku0nb.png',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671448/hxtkrje5cwkdajyfuhg2.jpg',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671449/np7kvtcnusdnrowlkb3n.jpg',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671476/zecbk2j18ab83zpzhhum.jpg',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671226/z2ljjartk4vgpbvanae2.png',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671227/glra05whzqe8ilaqhokc.jpg',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671228/b5dpnbnsxbkxuv0pff4g.jpg',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671255/hkzptty2mrrdqgcjnvbv.jpg',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671279/rfu0ezziafbr0xwcjtce.png',
];
const URBAN = [
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671533/jx0ic3w3sdaodjkbwfii.jpg',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671535/slzh0lbrkxaq2ogh9p81.jpg',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671536/r26fclszliusv87dophg.jpg',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671537/v8fzf32x11f4eefvpryk.jpg',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671538/sh2jvuvx9kyyuuif8fcl.jpg',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671539/mfk7anxdg0iwwur7syy8.jpg',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671540/xry7nw1bnp0fzws8vssb.jpg',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671541/tqa5xda6efa3hswoldsh.jpg',
];
const GARDEN = [
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671436/g1bzoz3cahba47gm9h6h.png',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671438/m680ugfj3ouacdvvgfun.png',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671439/nhmwwlfahgea7q8quyvr.jpg',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671440/hltlq9hcoedownpjryky.jpg',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671441/lpifn67ym262qt6ca4co.jpg',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671410/sztcq2i85onlew1jokqb.png',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671412/bjjkvffqxnnoijfb39tz.png',
];
const ARTWORK = [
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671218/wymbkpzgdmlov1gnysd3.jpg',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671220/krdjhrj99xfciaznt6kx.jpg',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671222/pxdn0m1hrnqmlvkc7fw8.jpg',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671223/ak3jf6chgziopsdiap66.jpg',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671224/i7evyck1uaddigui7bkk.png',
  'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671218/wymbkpzgdmlov1gnysd3.jpg',
];

export const projects = [
  // ── GOLF ──────────────────────────────────────────────────────────────────
  {
    id: 'golf-brg-danang',
    slug: 'golf-brg-danang',
    title: 'Sân Golf BRG Đà Nẵng',
    titleEn: 'BRG Da Nang Golf Course',
    category: 'Golf',
    location: 'Đà Nẵng',
    area: '—',
    duration: '—',
    client: 'BRG Group',
    year: '2015',
    image: GOLF[0].replace('w=1200', 'w=800'),
    images: [GOLF[0], GOLF[1], GOLF[2], GOLF[3], GOLF[4], GOLF[5]],
    description: 'Thi công cảnh quan và hệ thống tưới tiêu tự động Rainbird cho 18 lỗ golf BRG tại Đà Nẵng — đạt tiêu chuẩn quốc tế về cỏ và hệ thống tưới.',
    descriptionEn: 'Landscape construction and Rainbird automatic irrigation for all 18 holes of BRG Da Nang Golf Course — meeting international turf and irrigation standards.',
    articles: [],
  },
  {
    id: 'golf-bana-suoi-mo',
    slug: 'golf-bana-suoi-mo',
    title: 'Sân Golf Bà Nà – Suối Mơ',
    titleEn: 'Ba Na Hills – Suoi Mo Golf Course',
    category: 'Golf',
    location: 'Đà Nẵng',
    area: '—',
    duration: '—',
    client: 'Sun Group',
    year: '2017',
    image: GOLF[1].replace('w=1200', 'w=800'),
    images: [GOLF[1], GOLF[4], GOLF[7], GOLF[8], GOLF[0], GOLF[9]],
    description: 'Thi công cảnh quan và hệ thống tưới tiêu cho sân golf Bà Nà – Suối Mơ trong quần thể khu du lịch Bà Nà Hills của Sun Group.',
    descriptionEn: "Landscape construction and irrigation systems for the Ba Na Hills – Suoi Mo Golf Course within Sun Group's Ba Na Hills resort complex.",
    articles: [],
  },
  {
    id: 'golf-laguna-lang-co',
    slug: 'golf-laguna-lang-co',
    title: 'Sân Golf Laguna Lăng Cô',
    titleEn: 'Laguna Lăng Cô Golf Course',
    category: 'Golf',
    location: 'Thừa Thiên Huế',
    area: '—',
    duration: '—',
    client: 'Laguna Vietnam',
    year: '2016',
    image: GOLF[2].replace('w=1200', 'w=800'),
    images: [GOLF[2], GOLF[3], GOLF[8], GOLF[1], GOLF[6], GOLF[5]],
    description: 'Cảnh quan và hệ thống tưới tiêu Rainbird cho sân golf 18 lỗ tại khu nghỉ dưỡng Laguna Lăng Cô — kết hợp giữa cảnh quan tự nhiên và tiêu chuẩn thi đấu quốc tế.',
    descriptionEn: '18-hole golf course landscape and Rainbird irrigation at Laguna Lăng Cô Resort — blending natural scenery with international tournament standards.',
    articles: [],
  },
  {
    id: 'golf-clb-danang',
    slug: 'golf-clb-danang',
    title: 'Câu Lạc Bộ Golf Đà Nẵng (The Dunes)',
    titleEn: 'Da Nang Golf Club – The Dunes',
    category: 'Golf',
    location: 'Ngũ Hành Sơn, Đà Nẵng',
    area: '—',
    duration: '—',
    client: 'VinaCapital',
    year: '2010',
    image: GOLF[4].replace('w=1200', 'w=800'),
    images: [GOLF[4], GOLF[7], GOLF[9], GOLF[0], GOLF[5], GOLF[1]],
    description: 'Thi công cảnh quan và bảo dưỡng sân golf The Dunes — một trong những sân golf ven biển đẳng cấp nhất miền Trung Việt Nam.',
    descriptionEn: 'Landscape construction and maintenance for The Dunes golf course — one of the finest beachside golf courses in Central Vietnam.',
    articles: [],
  },
  {
    id: 'golf-montgomerie-links',
    slug: 'golf-montgomerie-links',
    title: 'Sân Golf Montgomerie Links',
    titleEn: 'Montgomerie Links Golf Course',
    category: 'Golf',
    location: 'Điện Bàn, Quảng Nam',
    area: '—',
    duration: '—',
    client: 'VinaCapital / Montgomerie Links Vietnam',
    year: '2012',
    image: GOLF[6].replace('w=1200', 'w=800'),
    images: [GOLF[6], GOLF[3], GOLF[5], GOLF[9], GOLF[2], GOLF[8]],
    description: 'Thi công cảnh quan và thảm cỏ cho sân golf 18 lỗ Montgomerie Links — thiết kế bởi huyền thoại Colin Montgomerie, nằm giữa đồng bằng ven biển Quảng Nam.',
    descriptionEn: 'Turf and landscape construction for the 18-hole Montgomerie Links course — designed by legend Colin Montgomerie, set among the coastal plains of Quang Nam.',
    articles: [],
  },
  {
    id: 'golf-flc-quy-nhon',
    slug: 'golf-flc-quy-nhon',
    title: 'Sân Golf FLC Quy Nhơn',
    titleEn: 'FLC Quy Nhon Golf Course',
    category: 'Golf',
    location: 'Quy Nhơn, Bình Định',
    area: '—',
    duration: '—',
    client: 'FLC Group',
    year: '2019',
    image: GOLF[8].replace('w=1200', 'w=800'),
    images: [GOLF[8], GOLF[0], GOLF[5], GOLF[7], GOLF[3], GOLF[6]],
    description: 'Cảnh quan và hệ thống tưới tự động cho sân golf ven biển FLC Quy Nhơn — tích hợp cảnh quan biển và thảm cỏ Zoysia đạt tiêu chuẩn thi đấu.',
    descriptionEn: 'Landscape and automatic irrigation for FLC Quy Nhon beachside golf course — integrating coastal scenery with tournament-grade Zoysia turf.',
    articles: [],
  },

  // ── RESORT ────────────────────────────────────────────────────────────────
  {
    id: 'laguna-lang-co',
    slug: 'laguna-lang-co',
    title: 'Khu Nghỉ Dưỡng Laguna Lăng Cô',
    titleEn: 'Laguna Lăng Cô Resort',
    category: 'Resort',
    location: 'Phú Lộc, Thừa Thiên Huế',
    area: '280 ha',
    duration: '—',
    client: 'Laguna Vietnam',
    year: '2013',
    image: RESORT[0].replace('w=1200', 'w=800'),
    images: [RESORT[0], RESORT[1], RESORT[2], RESORT[3], RESORT[7], GARDEN[1]],
    description: 'Thiết kế và thi công cảnh quan toàn bộ khu nghỉ dưỡng Laguna Lăng Cô rộng 280 ha — cảnh quan resort, vườn biệt thự và hành lang cây xanh dọc bãi biển.',
    descriptionEn: 'Full landscape design and construction for the 280-ha Laguna Lăng Cô Resort — resort greenery, villa gardens, and beachfront green corridors.',
    articles: [],
  },
  {
    id: 'ocean-villas-danang',
    slug: 'ocean-villas-danang',
    title: 'The Ocean Villas Đà Nẵng',
    titleEn: 'The Ocean Villas Da Nang',
    category: 'Resort',
    location: 'Ngũ Hành Sơn, Đà Nẵng',
    area: '150 ha',
    duration: '—',
    client: 'VinaCapital',
    year: '2014',
    image: RESORT[1].replace('w=1200', 'w=800'),
    images: [RESORT[1], RESORT[2], RESORT[4], RESORT[3], GARDEN[0], RESORT[8]],
    description: 'Cảnh quan biệt thự nghỉ dưỡng cao cấp The Ocean Villas — thiết kế vườn riêng từng căn biệt thự, hồ bơi infinity và hành lang cây xanh nội khu.',
    descriptionEn: 'Premium resort villa landscaping at The Ocean Villas — individual villa gardens, infinity pools, and internal green corridors.',
    articles: [],
  },
  {
    id: 'fiore-phan-thiet',
    slug: 'fiore-phan-thiet',
    title: 'Fiore Healthy Phan Thiết Resort',
    titleEn: 'Fiore Healthy Phan Thiet Resort',
    category: 'Resort',
    location: 'Phan Thiết, Bình Thuận',
    area: '1.8 ha',
    duration: '—',
    client: 'Công ty CP Du Lịch Ngọc Sơn',
    year: '2021',
    image: RESORT[2].replace('w=1200', 'w=800'),
    images: [RESORT[2], RESORT[0], GARDEN[1], RESORT[5], RESORT[8], GARDEN[3]],
    description: 'Thiết kế và thi công cảnh quan khu nghỉ dưỡng Fiore Healthy tại Phan Thiết — cảnh quan nhiệt đới, vườn wellness và không gian nghỉ dưỡng xanh hài hòa.',
    descriptionEn: 'Landscape design and construction for Fiore Healthy Resort, Phan Thiet — tropical landscaping, wellness garden, and harmonious green resort spaces.',
    articles: [],
  },
  {
    id: 'movenpick-novaworld',
    slug: 'movenpick-novaworld',
    title: 'Khách Sạn Movenpick Novaworld Phan Thiết',
    titleEn: 'Movenpick Hotel Novaworld Phan Thiet',
    category: 'Resort',
    location: 'Phan Thiết',
    area: '—',
    duration: '—',
    client: 'Delta-Valley Binh Thuan',
    year: '2022',
    image: RESORT[3].replace('w=1200', 'w=800'),
    images: [RESORT[3], RESORT[4], RESORT[7], RESORT[1], RESORT[8], GARDEN[2]],
    description: 'Cảnh quan khách sạn Movenpick thuộc quần thể Novaworld Phan Thiết — thiết kế và thi công hành lang cây xanh, pool garden và sân vườn sảnh đón.',
    descriptionEn: 'Landscape works for Movenpick Hotel within the Novaworld Phan Thiet complex — green corridors, pool garden, and lobby forecourt landscaping.',
    articles: [],
  },
  {
    id: 'hoiana-maintenance',
    slug: 'hoiana-maintenance',
    title: 'HOIANA – Bảo Dưỡng Cảnh Quan',
    titleEn: 'HOIANA Resort Landscape Maintenance',
    category: 'Resort',
    location: 'Hội An, Quảng Nam',
    area: '—',
    duration: '—',
    client: 'HOIANA',
    year: '2021',
    image: RESORT[5].replace('w=1200', 'w=800'),
    images: [RESORT[5], RESORT[6], RESORT[7], RESORT[0], RESORT[8], GARDEN[4]],
    description: 'Dịch vụ bảo dưỡng cảnh quan dài hạn cho khu nghỉ dưỡng HOIANA tại Hội An — duy trì chất lượng cây xanh, thảm cỏ và hệ sinh thái cảnh quan toàn khu.',
    descriptionEn: "Long-term landscape maintenance services for HOIANA Resort, Hoi An — maintaining greenery quality, turf, and the resort's complete landscape ecosystem.",
    articles: [],
  },
  {
    id: 'intercontinental-danang',
    slug: 'intercontinental-danang',
    title: 'InterContinental Đà Nẵng Sun Peninsula',
    titleEn: 'InterContinental Da Nang Sun Peninsula',
    category: 'Resort',
    location: 'Sơn Trà, Đà Nẵng',
    area: '39 ha',
    duration: '—',
    client: 'Sun Group',
    year: '2014',
    image: RESORT[6].replace('w=1200', 'w=800'),
    images: [RESORT[6], RESORT[0], RESORT[4], GARDEN[0], RESORT[2], RESORT[7]],
    description: 'Thi công cảnh quan nhiệt đới cho khu nghỉ dưỡng 5 sao InterContinental trên bán đảo Sơn Trà — cảnh quan hoà nhập với rừng nhiệt đới tự nhiên.',
    descriptionEn: 'Tropical landscape construction for the 5-star InterContinental resort on Son Tra Peninsula — landscaping integrated with the natural tropical forest.',
    articles: [],
  },
  {
    id: 'fusion-resort-cam-ranh',
    slug: 'fusion-resort-cam-ranh',
    title: 'Fusion Resort Cam Ranh',
    titleEn: 'Fusion Resort Cam Ranh',
    category: 'Resort',
    location: 'Cam Ranh, Khánh Hòa',
    area: '—',
    duration: '—',
    client: 'Fusion Resorts',
    year: '2018',
    image: RESORT[8].replace('w=1200', 'w=800'),
    images: [RESORT[8], RESORT[1], GARDEN[1], RESORT[5], RESORT[3], GARDEN[5]],
    description: 'Thiết kế và thi công cảnh quan resort all-spa Fusion tại Cam Ranh — vườn thiền, đường dạo ven biển và không gian cây xanh hài hòa với kiến trúc.',
    descriptionEn: 'Landscape design and construction for Fusion Resort Cam Ranh — zen garden, beachside walkways, and greenery harmonising with the architecture.',
    articles: [],
  },

  // ── URBAN ─────────────────────────────────────────────────────────────────
  {
    id: 'hue-traffic-landscape',
    slug: 'hue-traffic-landscape',
    title: 'Cảnh Quan Đường Giao Thông TP Huế',
    titleEn: 'Hue City Traffic Road Landscape',
    category: 'Urban',
    location: 'TP Huế, Thừa Thiên Huế',
    area: '—',
    duration: '—',
    client: 'Ban Môi Trường & Đô Thị Huế',
    year: '2015',
    image: URBAN[0].replace('w=1200', 'w=800'),
    images: [URBAN[0], URBAN[1], URBAN[2], URBAN[3], URBAN[4], URBAN[5]],
    description: 'Cảnh quan hoá các tuyến đường giao thông trọng điểm của thành phố Huế — trồng cây, thảm cỏ, hoa và thiết kế dải phân cách đô thị xanh.',
    descriptionEn: 'Landscaping of key traffic roads in Hue City — tree planting, turf, flowers, and green median strip design across major urban corridors.',
    articles: [],
  },
  {
    id: 'ngu-ha-river-hue',
    slug: 'ngu-ha-river-hue',
    title: 'Cải Tạo Sông Ngự Hà TP Huế',
    titleEn: 'Ngu Ha River Renovation, Hue City',
    category: 'Urban',
    location: 'TP Huế',
    area: '—',
    duration: '—',
    client: 'Ban Môi Trường & Đô Thị Huế',
    year: '2018',
    image: URBAN[1].replace('w=1200', 'w=800'),
    images: [URBAN[1], URBAN[0], URBAN[5], URBAN[6], URBAN[7], URBAN[2]],
    description: 'Cải tạo và cảnh quan hoá dọc bờ sông Ngự Hà — tạo hành lang xanh đô thị, lối đi bộ ven sông và không gian công cộng mới cho người dân Huế.',
    descriptionEn: 'Renovation and landscaping along the Ngu Ha River bank — creating an urban green corridor, riverside walkways, and new public spaces for Hue residents.',
    articles: [],
  },
  {
    id: 'manor-crown-hue',
    slug: 'manor-crown-hue',
    title: 'The Manor Crown Huế',
    titleEn: 'The Manor Crown Hue',
    category: 'Urban',
    location: 'Huế',
    area: '—',
    duration: '—',
    client: 'BIM Group',
    year: '2019',
    image: URBAN[2].replace('w=1200', 'w=800'),
    images: [URBAN[2], URBAN[3], URBAN[4], URBAN[5], GARDEN[1], URBAN[6]],
    description: 'Thiết kế và thi công cảnh quan khu đô thị cao cấp The Manor Crown tại Huế — cảnh quan nội khu, vườn công cộng và cây xanh đường nội bộ.',
    descriptionEn: 'Landscape design and construction for The Manor Crown premium urban development in Hue — internal landscape, public gardens, and street trees.',
    articles: [],
  },
  {
    id: 'vinpearl-phu-quoc-urban',
    slug: 'vinpearl-phu-quoc-urban',
    title: 'Khu Đô Thị Vinpearl Phú Quốc',
    titleEn: 'Vinpearl Phu Quoc Urban Development',
    category: 'Urban',
    location: 'Phú Quốc, Kiên Giang',
    area: '—',
    duration: '—',
    client: 'Vingroup',
    year: '2020',
    image: URBAN[4].replace('w=1200', 'w=800'),
    images: [URBAN[4], URBAN[6], URBAN[7], URBAN[0], GARDEN[2], URBAN[3]],
    description: 'Cảnh quan đô thị cho khu phức hợp Vinpearl tại Phú Quốc — trồng cây đường phố, công viên nội khu và hành lang xanh kết nối các tiện ích.',
    descriptionEn: 'Urban landscaping for the Vinpearl complex in Phu Quoc — street trees, internal parks, and green corridors connecting amenities.',
    articles: [],
  },

  // ── CONSTRUCTION ──────────────────────────────────────────────────────────
  {
    id: 'casamia-hoi-an',
    slug: 'casamia-hoi-an',
    title: 'Khu Đô Thị Casamia Hội An',
    titleEn: 'Casamia Hoi An Urban Area',
    category: 'Construction',
    location: 'Cẩm Thanh, Hội An, Quảng Nam',
    area: '6.4 ha',
    duration: '—',
    client: 'Đạt Phương Corp',
    year: '2020',
    image: URBAN[3].replace('w=1200', 'w=800'),
    images: [URBAN[3], URBAN[4], GARDEN[1], GARDEN[0], URBAN[1], URBAN[7]],
    description: 'Thi công cảnh quan và hạ tầng xanh cho khu đô thị Casamia tại Hội An — cảnh quan đường nội khu, công viên trung tâm và hành lang cây xanh 6.4 ha.',
    descriptionEn: 'Landscape and green infrastructure construction for the Casamia urban development in Hoi An — internal road landscaping, central park, and 6.4-ha green corridors.',
    articles: [],
  },
  {
    id: 'seava-ho-tram',
    slug: 'seava-ho-tram',
    title: 'Seava Hồ Tràm Strip',
    titleEn: 'Seava Ho Tram Strip',
    category: 'Construction',
    location: 'Hồ Tràm, Bà Rịa - Vũng Tàu',
    area: '—',
    duration: '—',
    client: 'Seava',
    year: '2021',
    image: GARDEN[3].replace('w=1200', 'w=800'),
    images: [GARDEN[3], RESORT[4], GARDEN[0], URBAN[5], RESORT[7], GARDEN[5]],
    description: 'Thi công cảnh quan và cây xanh cho tổ hợp Seava tại Hồ Tràm — cảnh quan ven biển, hệ thống tưới nhỏ giọt và vườn cây nhiệt đới đặc trưng.',
    descriptionEn: 'Landscape and planting works for the Seava Ho Tram complex — coastal landscaping, drip irrigation, and signature tropical garden.',
    articles: [],
  },
  {
    id: 'sunbay-park-ninh-thuan',
    slug: 'sunbay-park-ninh-thuan',
    title: 'Sun Bay Park Ninh Thuận',
    titleEn: 'Sun Bay Park Ninh Thuan',
    category: 'Construction',
    location: 'Ninh Thuận',
    area: '—',
    duration: '—',
    client: 'Sun Group',
    year: '2023',
    image: URBAN[6].replace('w=1200', 'w=800'),
    images: [URBAN[6], URBAN[7], GARDEN[4], GARDEN[1], RESORT[6], URBAN[4]],
    description: 'Thi công cảnh quan khu nghỉ dưỡng và công viên Sun Bay tại Ninh Thuận — hệ thống tưới thông minh, vườn xương rồng và cảnh quan sa mạc nhiệt đới.',
    descriptionEn: 'Landscape construction for Sun Bay Park resort in Ninh Thuan — smart irrigation, cactus garden, and tropical desert landscaping.',
    articles: [],
  },

  // ── ARTWORK ───────────────────────────────────────────────────────────────
  {
    id: 'cau-dat-farm-dalat',
    slug: 'cau-dat-farm-dalat',
    title: 'Cầu Đất Farm – Đà Lạt',
    titleEn: 'Cau Dat Farm – Da Lat',
    category: 'Artwork',
    location: 'Trạm Hành, Đà Lạt, Lâm Đồng',
    area: '230 ha',
    duration: '—',
    client: 'Novaland / Cau Dat Tea JSC',
    year: '2022',
    image: GARDEN[0].replace('w=1200', 'w=800'),
    images: [GARDEN[0], GARDEN[2], GARDEN[3], GARDEN[4], GARDEN[5], GARDEN[6]],
    description: 'Thi công cảnh quan và artwork cho khu nông trại sinh thái Cầu Đất rộng 230 ha tại Đà Lạt — công trình nghệ thuật iconic hoà quyện với địa hình đồi chè.',
    descriptionEn: 'Landscape and artwork construction for the 230-ha Cau Dat eco-farm in Da Lat — iconic art installations blending with the tea-plantation terrain.',
    articles: [],
  },
  {
    id: 'tropicana-novaworld',
    slug: 'tropicana-novaworld',
    title: 'The Tropicana – Novaworld Hồ Tràm',
    titleEn: 'The Tropicana – Novaworld Ho Tram',
    category: 'Artwork',
    location: 'Hồ Tràm, Bà Rịa - Vũng Tàu',
    area: '—',
    duration: '—',
    client: 'Novaland',
    year: '2022',
    image: ARTWORK[0].replace('w=1200', 'w=800'),
    images: [ARTWORK[0], ARTWORK[1], ARTWORK[2], ARTWORK[3], ARTWORK[4], ARTWORK[5]],
    description: 'Thi công cảnh quan và công trình Artwork biểu tượng cho khu The Tropicana tại Novaworld Hồ Tràm — tạo dấu ấn nhận diện độc đáo cho dự án nghỉ dưỡng ven biển.',
    descriptionEn: 'Landscape and iconic Artwork construction for The Tropicana at Novaworld Ho Tram — creating a unique landmark identity for the beachside resort development.',
    articles: [],
  },
  {
    id: 'sunworld-bana-hills',
    slug: 'sunworld-bana-hills',
    title: 'Sun World Bà Nà Hills – Artwork Cảnh Quan',
    titleEn: 'Sun World Ba Na Hills – Landscape Artwork',
    category: 'Artwork',
    location: 'Đà Nẵng',
    area: '—',
    duration: '—',
    client: 'Sun Group',
    year: '2020',
    image: ARTWORK[2].replace('w=1200', 'w=800'),
    images: [ARTWORK[2], ARTWORK[4], ARTWORK[1], GARDEN[2], ARTWORK[5], ARTWORK[3]],
    description: 'Thi công các hạng mục Artwork và cảnh quan đặc biệt tại Sun World Bà Nà Hills — tạo điểm nhấn nghệ thuật iconic trong không gian giải trí độc đáo.',
    descriptionEn: 'Construction of Artwork and special landscape features at Sun World Ba Na Hills — creating iconic artistic highlights in a unique entertainment landscape.',
    articles: [],
  },
  {
    id: 'hoiana-artwork',
    slug: 'hoiana-artwork',
    title: 'HOIANA – Artwork & Cảnh Quan Đặc Biệt',
    titleEn: 'HOIANA – Artwork & Feature Landscape',
    category: 'Artwork',
    location: 'Hội An, Quảng Nam',
    area: '—',
    duration: '—',
    client: 'HOIANA',
    year: '2022',
    image: ARTWORK[4].replace('w=1200', 'w=800'),
    images: [ARTWORK[4], ARTWORK[0], ARTWORK[3], RESORT[5], ARTWORK[2], GARDEN[3]],
    description: 'Thiết kế và thi công các công trình Artwork cảnh quan đặc biệt cho khu nghỉ dưỡng HOIANA — kết hợp nghệ thuật đương đại và văn hóa địa phương Hội An.',
    descriptionEn: 'Design and construction of feature Artwork for HOIANA Resort — blending contemporary art with the local culture and heritage of Hoi An.',
    articles: [],
  },

];

export const timelineItems = [
  {
    year: '2007–2008',
    title: 'Khởi nghiệp',
    titleEn: 'Founding',
    description: 'Thành lập công ty tại Đà Nẵng với hoạt động nhập khẩu và phân phối hoa. Khởi đầu cung ứng lao động cảnh quan mềm — cây xanh, hoa, thảm cỏ cho các dự án bất động sản đầu tiên.',
    descriptionEn: 'Founded in Da Nang with flower import and distribution. Began supplying soft landscape labour — trees, flowers, and turf for the first real estate projects.',
  },
  {
    year: '2009–2013',
    title: 'Hình thành và phát triển',
    titleEn: 'Formation & Growth',
    description: 'Đầu tư vườn ươm cây giống quy mô lớn, xây dựng đội ngũ kỹ thuật chuyên nghiệp. Ký kết hợp tác với các tập đoàn bất động sản và resort lớn tại miền Trung Việt Nam.',
    descriptionEn: 'Invested in a large-scale plant nursery and built a professional technical team. Established partnerships with major real estate groups and resorts in Central Vietnam.',
  },
  {
    year: '2014–2018',
    title: 'Mở rộng toàn diện',
    titleEn: 'Comprehensive Expansion',
    description: 'Mở rộng sang hạ tầng cảnh quan cứng, hệ thống tưới tiêu tự động Rainbird và sân golf. Khai trương văn phòng Huế, tiếp cận thị trường resort và sân golf quốc tế tại miền Trung.',
    descriptionEn: 'Expanded into hardscape infrastructure, Rainbird automatic irrigation systems, and golf courses. Opened a Hue office, reaching the international resort and golf market in Central Vietnam.',
  },
  {
    year: '2018–2022',
    title: 'Nhà thầu chính đa lĩnh vực',
    titleEn: 'Full-Service Main Contractor',
    description: 'Trở thành tổng thầu thiết kế + thi công toàn diện. Mở rộng sang MEP, Artwork công trình và hợp tác đối tác ASEAN. Vượt qua thử thách COVID-19 để tiếp tục phát triển bền vững.',
    descriptionEn: 'Became a comprehensive design+build main contractor. Expanded into MEP, Artwork installations, and ASEAN partnerships. Overcame COVID-19 challenges while continuing sustainable growth.',
  },
  {
    year: '2023–nay',
    title: 'Tăng trưởng bền vững',
    titleEn: 'Sustainable Growth',
    description: 'Tái cơ cấu tổ chức theo mô hình hệ sinh thái Lapla Group, áp dụng tiêu chuẩn ISO, đầu tư hệ thống CNTT và vận hành chuyên nghiệp. Củng cố vị thế dẫn đầu thị trường cảnh quan xanh bền vững.',
    descriptionEn: 'Restructured into the Lapla Group ecosystem model, applied ISO standards, invested in IT systems and professional operations. Consolidated market leadership in sustainable green landscaping.',
  },
];

export const partners = [
  {
    name: 'VinaCapital',
    sector: 'Đầu tư & Bất động sản', sectorEn: 'Investment & Real Estate',
    descVi: 'Tập đoàn đầu tư và bất động sản hàng đầu Việt Nam, chủ đầu tư nhiều khu nghỉ dưỡng và khu đô thị cao cấp.',
    descEn: 'Leading investment and real estate group in Vietnam, developer of many premium resorts and urban areas.',
    founded: 2003, hq: 'TP. Hồ Chí Minh, Việt Nam',
    statLabelVi: 'Tổng tài sản quản lý', statLabelEn: 'Assets under management',
    statValue: '~4 tỷ USD',
    projectsVi: ['Danang Golf Club – cảnh quan sân golf 36 lỗ', 'VinaCapital Resort Hội An – cây xanh & tiểu cảnh', 'Sky Villas Đà Nẵng – cảnh quan khuôn viên'],
    projectsEn: ['Danang Golf Club – 36-hole golf landscape', 'VinaCapital Resort Hoi An – planting & softscape', 'Sky Villas Da Nang – estate landscaping'],
    highlightVi: 'Chủ đầu tư lớn nhất tại Đà Nẵng, hợp tác với Lapla từ 2010.',
    highlightEn: 'Largest investor in Da Nang, partnering with Lapla since 2010.',
  },
  {
    name: 'Novaland',
    sector: 'Phát triển Bất động sản', sectorEn: 'Real Estate Developer',
    descVi: 'Tập đoàn phát triển bất động sản lớn tại Việt Nam với nhiều dự án nghỉ dưỡng và đô thị trên toàn quốc.',
    descEn: 'One of the largest real estate developers in Vietnam with resort and urban projects nationwide.',
    founded: 1992, hq: 'TP. Hồ Chí Minh, Việt Nam',
    statLabelVi: 'Dự án phát triển', statLabelEn: 'Development projects',
    statValue: '50+ dự án',
    projectsVi: ['NovaWorld Hồ Tràm – cảnh quan khu đô thị biển', 'Aqua City Đồng Nai – mảng xanh & công viên nội khu', 'NovaBeach Cam Ranh – softscape resort'],
    projectsEn: ['NovaWorld Ho Tram – coastal urban landscape', 'Aqua City Dong Nai – greenery & internal parks', 'NovaBeach Cam Ranh – resort softscape'],
    highlightVi: 'Một trong những chủ đầu tư bất động sản nghỉ dưỡng lớn nhất Việt Nam.',
    highlightEn: 'One of the largest resort real estate developers in Vietnam.',
  },
  {
    name: 'BRG Group',
    sector: 'Tập đoàn Đa ngành', sectorEn: 'Diversified Conglomerate',
    descVi: 'Tập đoàn BRG sở hữu nhiều sân golf và khu nghỉ dưỡng cao cấp, là đối tác chiến lược lâu năm của Lapla.',
    descEn: 'BRG Group owns multiple premium golf courses and resorts, a long-term strategic partner of Lapla.',
    founded: 1993, hq: 'Hà Nội, Việt Nam',
    statLabelVi: 'Sân golf sở hữu', statLabelEn: 'Golf courses owned',
    statValue: '7 sân golf',
    projectsVi: ['Đảo Vua Golf – tái cảnh quan 18 lỗ', 'BRG Da Nang Golf Resort – cảnh quan sân & khuôn viên', 'Hilton Hanoi Opera – cây xanh & sân vườn khách sạn'],
    projectsEn: ['Kings Island Golf – 18-hole landscape renovation', 'BRG Da Nang Golf Resort – course & estate landscape', 'Hilton Hanoi Opera – hotel green & garden works'],
    highlightVi: 'Đối tác golf chiến lược hàng đầu của Lapla tại miền Bắc.',
    highlightEn: 'Lapla\'s leading strategic golf partner in Northern Vietnam.',
  },
  {
    name: 'Laguna Lăng Cô',
    sector: 'Khu nghỉ dưỡng Quốc tế', sectorEn: 'International Resort',
    descVi: 'Khu nghỉ dưỡng đẳng cấp quốc tế tại Lăng Cô, Thừa Thiên Huế. Lapla đã thi công cảnh quan sân golf và khuôn viên resort.',
    descEn: 'World-class resort in Lang Co, Thua Thien Hue. Lapla executed landscape and golf course works.',
    founded: 2013, hq: 'Lăng Cô, Thừa Thiên Huế, Việt Nam',
    statLabelVi: 'Diện tích khu nghỉ dưỡng', statLabelEn: 'Resort area',
    statValue: '280 ha',
    projectsVi: ['Sân golf 18 lỗ Laguna – cảnh quan toàn bộ', 'Biệt thự ven biển – cây xanh & hồ cảnh', 'Khu villa Banyan Tree – tiểu cảnh nhiệt đới'],
    projectsEn: ['Laguna 18-hole golf – full landscape works', 'Beachfront villas – planting & water features', 'Banyan Tree villa zone – tropical softscape'],
    highlightVi: 'Dự án cảnh quan sân golf quốc tế đầu tiên Lapla thực hiện tại miền Trung.',
    highlightEn: 'First international golf landscape project Lapla completed in Central Vietnam.',
  },
  {
    name: 'Sun Group',
    sector: 'Du lịch & Giải trí', sectorEn: 'Tourism & Entertainment',
    descVi: 'Tập đoàn Sun Group sở hữu Bà Nà Hills, Phú Quốc Discovery và nhiều điểm đến nổi tiếng trên toàn quốc.',
    descEn: 'Sun Group owns Ba Na Hills, Phu Quoc Discovery, and many landmark destinations across Vietnam.',
    founded: 2007, hq: 'Hà Nội, Việt Nam',
    statLabelVi: 'Điểm đến biểu tượng', statLabelEn: 'Iconic destinations',
    statValue: '20+ dự án',
    projectsVi: ['Bà Nà Hills – cảnh quan vườn hoa & thảm cỏ', 'Sun World Phú Quốc – cây xanh khu vui chơi', 'Premier Village Đà Nẵng – sân vườn biệt thự biển'],
    projectsEn: ['Ba Na Hills – flower garden & lawn landscape', 'Sun World Phu Quoc – theme park greenery', 'Premier Village Da Nang – beachfront villa gardens'],
    highlightVi: 'Chủ đầu tư của Cầu Vàng nổi tiếng thế giới tại Bà Nà Hills.',
    highlightEn: 'Developer of the world-famous Golden Bridge at Ba Na Hills.',
  },
  {
    name: 'Hung Thinh Corp',
    sector: 'Bất động sản', sectorEn: 'Real Estate',
    descVi: 'Tập đoàn Hưng Thịnh – nhà phát triển bất động sản lớn tại TP.HCM và các tỉnh thành miền Nam.',
    descEn: 'Hung Thinh Corporation – major real estate developer in Ho Chi Minh City and southern provinces.',
    founded: 2002, hq: 'TP. Hồ Chí Minh, Việt Nam',
    statLabelVi: 'Dự án đã bàn giao', statLabelEn: 'Delivered projects',
    statValue: '60+ dự án',
    projectsVi: ['MerryLand Quy Nhơn – cảnh quan resort & marina', 'The Maris Vũng Tàu – sân vườn căn hộ cao tầng', 'Charm Resort Hồ Tràm – softscape khu nghỉ dưỡng'],
    projectsEn: ['MerryLand Quy Nhon – resort & marina landscape', 'The Maris Vung Tau – high-rise apartment gardens', 'Charm Resort Ho Tram – resort softscape'],
    highlightVi: 'Một trong top 5 nhà phát triển bất động sản lớn nhất miền Nam.',
    highlightEn: 'One of the top 5 largest real estate developers in Southern Vietnam.',
  },
  {
    name: 'Fusion Resort',
    sector: 'Hospitality', sectorEn: 'Hospitality',
    descVi: 'Chuỗi resort cao cấp với triết lý "all-spa-inclusive" độc đáo, hoạt động tại Đà Nẵng, Cam Ranh và Phú Quốc.',
    descEn: 'Premium resort chain with a unique "all-spa-inclusive" philosophy, operating in Da Nang, Cam Ranh and Phu Quoc.',
    founded: 2008, hq: 'Đà Nẵng, Việt Nam',
    statLabelVi: 'Resort trong chuỗi', statLabelEn: 'Resorts in chain',
    statValue: '8 resort',
    projectsVi: ['Fusion Maia Đà Nẵng – cảnh quan nhiệt đới & hồ bơi', 'Fusion Resort Cam Ranh – vườn nhiệt đới ven biển', 'Fusion Suites Sài Gòn – sân vườn tầng mái'],
    projectsEn: ['Fusion Maia Da Nang – tropical & pool landscape', 'Fusion Resort Cam Ranh – beachside tropical garden', 'Fusion Suites Saigon – rooftop garden'],
    highlightVi: 'Thương hiệu resort Việt đầu tiên áp dụng mô hình "all-spa-inclusive".',
    highlightEn: 'First Vietnamese resort brand to apply the "all-spa-inclusive" model.',
  },
  {
    name: 'HOIANA',
    sector: 'Nghỉ dưỡng & Casino', sectorEn: 'Resort & Casino',
    descVi: 'Khu nghỉ dưỡng tích hợp HOIANA tại Quảng Nam – điểm đến sang trọng bậc nhất miền Trung Việt Nam.',
    descEn: 'HOIANA integrated resort complex in Quang Nam – the most luxurious destination in Central Vietnam.',
    founded: 2019, hq: 'Quảng Nam, Việt Nam',
    statLabelVi: 'Tổng vốn đầu tư', statLabelEn: 'Total investment',
    statValue: '4 tỷ USD',
    projectsVi: ['HOIANA Sands Golf – cảnh quan sân golf ven biển', 'Hoiana Hotel & Suites – cây xanh & hồ cảnh nội khu', 'Rosewood Hoi An – tiểu cảnh sang trọng & bờ biển'],
    projectsEn: ['HOIANA Sands Golf – beachside golf landscape', 'Hoiana Hotel & Suites – internal planting & water features', 'Rosewood Hoi An – luxury softscape & beachfront'],
    highlightVi: 'Khu tích hợp casino – resort duy nhất tại miền Trung, vốn đầu tư 4 tỷ USD.',
    highlightEn: 'The only integrated casino-resort in Central Vietnam, with $4 billion investment.',
  },
  {
    name: 'Radisson',
    sector: 'Khách sạn Quốc tế', sectorEn: 'International Hotel',
    descVi: 'Tập đoàn khách sạn quốc tế Radisson với nhiều thương hiệu cao cấp hoạt động tại Việt Nam.',
    descEn: 'International hotel group Radisson with multiple premium brands operating in Vietnam.',
    founded: 1960, hq: 'Brussels, Bỉ',
    statLabelVi: 'Khách sạn toàn cầu', statLabelEn: 'Global hotels',
    statValue: '1,700+ khách sạn',
    projectsVi: ['Radisson Blu Đà Nẵng – sân vườn & hồ bơi ngoài trời', 'Radisson Resort Phú Quốc – tiểu cảnh nhiệt đới', 'Park Inn Đà Nẵng – cảnh quan sân thượng & lối vào'],
    projectsEn: ['Radisson Blu Da Nang – outdoor garden & pool landscape', 'Radisson Resort Phu Quoc – tropical softscape', 'Park Inn Da Nang – rooftop & entrance landscape'],
    highlightVi: 'Hiện diện tại 120+ quốc gia, Lapla là đối tác cảnh quan tại Việt Nam.',
    highlightEn: 'Present in 120+ countries; Lapla is their landscape partner in Vietnam.',
  },
  {
    name: 'Minor International',
    sector: 'Hospitality & F&B', sectorEn: 'Hospitality & F&B',
    descVi: 'Tập đoàn Minor International – chuỗi khách sạn và nhà hàng cao cấp tại Việt Nam và châu Á.',
    descEn: 'Minor International – premium hotel and restaurant chain across Vietnam and Asia.',
    founded: 1978, hq: 'Bangkok, Thái Lan',
    statLabelVi: 'Khách sạn tại châu Á', statLabelEn: 'Hotels in Asia',
    statValue: '530+ khách sạn',
    projectsVi: ['Anantara Hội An – vườn nhiệt đới & hành lang cây xanh', 'NH Collection Đà Nẵng – cảnh quan mặt tiền & sảnh', 'Avani+ Quy Nhơn Resort – bãi biển & sân vườn biệt thự'],
    projectsEn: ['Anantara Hoi An – tropical garden & green corridors', 'NH Collection Da Nang – façade & lobby landscape', 'Avani+ Quy Nhon Resort – beach & villa garden works'],
    highlightVi: 'Vận hành thương hiệu Anantara và NH Collection tại nhiều tỉnh thành Việt Nam.',
    highlightEn: 'Operates Anantara and NH Collection brands across multiple Vietnamese provinces.',
  },
  {
    name: 'Obayashi Vietnam',
    sector: 'Xây dựng Quốc tế', sectorEn: 'International Construction',
    descVi: 'Công ty con của Tập đoàn Obayashi Nhật Bản – nhà thầu xây dựng uy tín hàng đầu tại Việt Nam.',
    descEn: "Subsidiary of Japan's Obayashi Corporation – one of the most reputable construction contractors in Vietnam.",
    founded: 1892, hq: 'Osaka, Nhật Bản',
    statLabelVi: 'Doanh thu tập đoàn mẹ', statLabelEn: 'Parent group revenue',
    statValue: '~18 tỷ USD/năm',
    projectsVi: ['Khu đô thị Phú Mỹ Hưng – cảnh quan đại lộ & công viên', 'Keangnam Landmark Hà Nội – sân vườn tòa nhà', 'Dự án hạ tầng metro TP.HCM – cây xanh đô thị'],
    projectsEn: ['Phu My Hung Township – boulevard & park landscape', 'Keangnam Landmark Hanoi – building green works', 'HCMC Metro Infrastructure – urban greenery'],
    highlightVi: 'Tập đoàn xây dựng lớn thứ 4 Nhật Bản, hợp tác cảnh quan với Lapla tại các công trình quy mô lớn.',
    highlightEn: "Japan's 4th largest construction group, collaborating with Lapla on large-scale landscape works.",
  },
  {
    name: 'Vicoland Group',
    sector: 'Bất động sản', sectorEn: 'Real Estate',
    descVi: 'Tập đoàn Vicoland phát triển nhiều dự án khu đô thị và nhà ở tại miền Trung Việt Nam.',
    descEn: 'Vicoland Group develops urban and residential projects in Central Vietnam.',
    founded: 2007, hq: 'Đà Nẵng, Việt Nam',
    statLabelVi: 'Dự án tại miền Trung', statLabelEn: 'Projects in Central Vietnam',
    statValue: '15+ dự án',
    projectsVi: ['The Ori Garden Đà Nẵng – cảnh quan khu dân cư', 'Vicoland Riverside – cây xanh & hành lang sông', 'Marina Complex Đà Nẵng – tiểu cảnh khuôn viên'],
    projectsEn: ['The Ori Garden Da Nang – residential landscape', 'Vicoland Riverside – greenery & riverside corridor', 'Marina Complex Da Nang – campus softscape'],
    highlightVi: 'Một trong những nhà phát triển bất động sản lâu đời nhất tại Đà Nẵng.',
    highlightEn: 'One of the longest-standing real estate developers in Da Nang.',
  },
  {
    name: 'Dat Phuong',
    sector: 'Bất động sản', sectorEn: 'Real Estate',
    descVi: 'Công ty Cổ phần Đất Phương – nhà phát triển bất động sản uy tín tại Đà Nẵng và khu vực miền Trung.',
    descEn: 'Dat Phuong JSC – a reputable real estate developer in Da Nang and the Central region.',
    founded: 2005, hq: 'Đà Nẵng, Việt Nam',
    statLabelVi: 'Diện tích đất phát triển', statLabelEn: 'Land area developed',
    statValue: '500+ ha',
    projectsVi: ['Khu đô thị Phú Mỹ An – cảnh quan đường nội khu', 'Đất Phương Liên Chiểu – cây xanh khu dân cư', 'Shophouse Đà Nẵng – tiểu cảnh mặt tiền'],
    projectsEn: ['Phu My An Township – internal road landscape', 'Dat Phuong Lien Chieu – residential greenery', 'Da Nang Shophouses – facade softscape'],
    highlightVi: 'Đối tác bất động sản nội địa lâu năm của Lapla tại khu vực Đà Nẵng.',
    highlightEn: 'Long-term local real estate partner of Lapla in the Da Nang area.',
  },
  {
    name: 'TTC Land',
    sector: 'Bất động sản', sectorEn: 'Real Estate',
    descVi: 'TTC Land (Thành Thành Công) – nhà phát triển bất động sản và khu du lịch sinh thái trên cả nước.',
    descEn: 'TTC Land (Thanh Thanh Cong) – real estate and eco-tourism developer nationwide.',
    founded: 1979, hq: 'TP. Hồ Chí Minh, Việt Nam',
    statLabelVi: 'Tập đoàn thành viên', statLabelEn: 'Member companies',
    statValue: '30+ công ty',
    projectsVi: ['TTC Sugar Resort Phan Thiết – cảnh quan eco-resort', 'Khu đô thị TTC Long An – cây xanh & mặt nước', 'Alma Resort Cam Ranh – softscape khuôn viên resort'],
    projectsEn: ['TTC Sugar Resort Phan Thiet – eco-resort landscape', 'TTC Long An Township – greenery & water features', 'Alma Resort Cam Ranh – resort campus softscape'],
    highlightVi: 'Sở hữu chuỗi resort sinh thái đường mía độc đáo tại Việt Nam.',
    highlightEn: 'Owns a unique sugarcane eco-resort chain across Vietnam.',
  },
  {
    name: 'Sacomreal',
    sector: 'Bất động sản', sectorEn: 'Real Estate',
    descVi: 'Sacomreal (SCR) – công ty bất động sản thuộc hệ sinh thái Sacombank, phát triển nhiều dự án căn hộ và resort.',
    descEn: 'Sacomreal (SCR) – real estate company in the Sacombank ecosystem, developing apartments and resort projects.',
    founded: 2002, hq: 'TP. Hồ Chí Minh, Việt Nam',
    statLabelVi: 'Vốn điều lệ', statLabelEn: 'Charter capital',
    statValue: '1,800 tỷ VNĐ',
    projectsVi: ['Khu nghỉ dưỡng Phan Thiết – cảnh quan bãi biển', 'Chung cư SCR TP.HCM – sân vườn & hồ bơi nội khu', 'Sacomreal Garden Hill – tiểu cảnh khu dân cư'],
    projectsEn: ['Phan Thiet Resort – beachfront landscape', 'SCR Apartments HCMC – internal garden & pool works', 'Sacomreal Garden Hill – residential softscape'],
    highlightVi: 'Niêm yết trên HOSE, thành viên hệ sinh thái tài chính Sacombank.',
    highlightEn: 'Listed on HOSE, member of the Sacombank financial ecosystem.',
  },
  {
    name: 'Six Senses',
    sector: 'Luxury Resort', sectorEn: 'Luxury Resort',
    descVi: 'Thương hiệu resort siêu sang Six Senses với triết lý du lịch bền vững và trải nghiệm thiên nhiên độc đáo.',
    descEn: 'Ultra-luxury resort brand Six Senses with a sustainable tourism philosophy and unique nature experiences.',
    founded: 1995, hq: 'Bangkok, Thái Lan (thuộc IHG)',
    statLabelVi: 'Resort trên toàn cầu', statLabelEn: 'Resorts worldwide',
    statValue: '22 resort',
    projectsVi: ['Six Senses Ninh Vân Bay – cảnh quan vách đá & bãi biển', 'Six Senses Côn Đảo – vườn nhiệt đới & hồ cảnh', 'Six Senses Cần Thơ – tiểu cảnh sông nước miền Tây'],
    projectsEn: ['Six Senses Ninh Van Bay – cliff & beachfront landscape', 'Six Senses Con Dao – tropical garden & water features', 'Six Senses Can Tho – Mekong-inspired water landscape'],
    highlightVi: 'Thương hiệu resort hạng nhất thế giới, Lapla cung cấp cây nhiệt đới đặc chủng.',
    highlightEn: 'World-class resort brand; Lapla supplies specialty tropical plants for their properties.',
  },
  {
    name: 'Marriott',
    sector: 'Khách sạn Quốc tế', sectorEn: 'International Hotel',
    descVi: 'Tập đoàn khách sạn Marriott International với hơn 30 thương hiệu khách sạn và khu nghỉ dưỡng cao cấp toàn cầu.',
    descEn: 'Marriott International hotel group with over 30 premium hotel and resort brands worldwide.',
    founded: 1927, hq: 'Bethesda, Maryland, Mỹ',
    statLabelVi: 'Khách sạn toàn cầu', statLabelEn: 'Hotels worldwide',
    statValue: '8,900+ khách sạn',
    projectsVi: ['JW Marriott Hà Nội – vườn cảnh quan & sảnh ngoài trời', 'Sheraton Đà Nẵng – cảnh quan bãi biển & hồ bơi', 'Marriott Bonvoy Phú Quốc – tiểu cảnh nhiệt đới'],
    projectsEn: ['JW Marriott Hanoi – outdoor garden & lobby landscape', 'Sheraton Da Nang – beach & pool landscape', 'Marriott Bonvoy Phu Quoc – tropical softscape'],
    highlightVi: 'Tập đoàn khách sạn lớn nhất thế giới, hiện diện tại 141 quốc gia.',
    highlightEn: "World's largest hotel group, present in 141 countries.",
  },
  {
    name: 'Hyatt',
    sector: 'Khách sạn Quốc tế', sectorEn: 'International Hotel',
    descVi: 'Tập đoàn Hyatt sở hữu nhiều thương hiệu khách sạn cao cấp, đang mở rộng mạnh tại Việt Nam.',
    descEn: 'Hyatt Corporation owns multiple premium hotel brands, with strong expansion in Vietnam.',
    founded: 1957, hq: 'Chicago, Illinois, Mỹ',
    statLabelVi: 'Khách sạn toàn cầu', statLabelEn: 'Hotels worldwide',
    statValue: '1,150+ khách sạn',
    projectsVi: ['Park Hyatt Sài Gòn – vườn sân thượng & tiểu cảnh', 'Hyatt Regency Đà Nẵng – bãi biển & hồ bơi ngoài trời', 'Alila Hội An – vườn nhiệt đới hữu cơ & mặt nước'],
    projectsEn: ['Park Hyatt Saigon – rooftop garden & softscape', 'Hyatt Regency Da Nang – beach & outdoor pool landscape', 'Alila Hoi An – organic tropical garden & water features'],
    highlightVi: 'Thương hiệu Alila (thuộc Hyatt) nổi tiếng tại Hội An với triết lý thiên nhiên bền vững.',
    highlightEn: 'Alila brand (under Hyatt) is renowned in Hoi An for its sustainable nature philosophy.',
  },
  {
    name: 'Seava Hồ Tràm',
    sector: 'Khu nghỉ dưỡng', sectorEn: 'Resort',
    descVi: 'Khu nghỉ dưỡng biển Seava tại Hồ Tràm, Bà Rịa – Vũng Tàu với cảnh quan thiên nhiên tuyệt đẹp.',
    descEn: 'Seava seaside resort at Ho Tram, Ba Ria – Vung Tau with stunning natural landscape.',
    founded: 2018, hq: 'Hồ Tràm, Bà Rịa – Vũng Tàu, Việt Nam',
    statLabelVi: 'Đường bờ biển sở hữu', statLabelEn: 'Private beachfront',
    statValue: '1.2 km bãi biển',
    projectsVi: ['Seava Beach Resort – cảnh quan bờ biển & hồ bơi tràn bờ', 'Khu villa Seava – vườn nhiệt đới riêng từng căn', 'Bãi biển riêng – cây dừa & thảm cỏ ven biển'],
    projectsEn: ['Seava Beach Resort – beachfront & infinity pool landscape', 'Seava Villas – individual tropical villa gardens', 'Private beach – coconut palms & coastal lawn works'],
    highlightVi: 'Resort biển cao cấp mới nổi tại Hồ Tràm, sở hữu 1.2 km bờ biển riêng.',
    highlightEn: 'Rising premium beach resort in Ho Tram with 1.2 km of private beachfront.',
  },
  {
    name: 'TonkinLand',
    sector: 'Bất động sản', sectorEn: 'Real Estate',
    descVi: 'TonkinLand – nhà phát triển bất động sản mới nổi tại miền Bắc và miền Trung Việt Nam.',
    descEn: 'TonkinLand – emerging real estate developer in Northern and Central Vietnam.',
    founded: 2015, hq: 'Hà Nội, Việt Nam',
    statLabelVi: 'Dự án đang triển khai', statLabelEn: 'Active projects',
    statValue: '8 dự án',
    projectsVi: ['Tonkin Lotus Lake – cảnh quan hồ sen & khu dân cư', 'The Eden Rose Hà Nội – sân vườn & hành lang xanh', 'TonkinLand Nghệ An – cây xanh khu đô thị mới'],
    projectsEn: ['Tonkin Lotus Lake – lotus lake & residential landscape', 'The Eden Rose Hanoi – gardens & green corridors', 'TonkinLand Nghe An – new urban greenery'],
    highlightVi: 'Đang mở rộng nhanh sang các tỉnh miền Trung với nhiều dự án quy mô lớn.',
    highlightEn: 'Rapidly expanding into Central Vietnam provinces with large-scale projects.',
  },
];

export const memberCompanies = [
  {
    abbr: 'LAPLA',
    name: 'Công ty CP Cảnh Quan LAPLA',
    tagline: 'Core · Landscape & Golf',
    description: 'Đơn vị cốt lõi của hệ sinh thái, chuyên thiết kế và thi công cảnh quan toàn diện, sân golf quốc tế, resort và khu đô thị tại Việt Nam.',
    descriptionEn: 'The core entity of the ecosystem, specialising in comprehensive landscape design and construction, international golf courses, resorts, and urban developments across Vietnam.',
    accent: '#16a34a',
  },
  {
    abbr: 'ANA',
    name: 'Công ty CP Xây Dựng An Nguyễn An',
    tagline: 'Construction & MEP',
    description: 'Đảm nhận các hạng mục xây dựng dân dụng, hạ tầng kỹ thuật và cơ điện lạnh (MEP) cho các dự án trong hệ sinh thái Lapla Group.',
    descriptionEn: 'Handles civil construction, technical infrastructure, and MEP (Mechanical, Electrical, Plumbing) works for projects within the Lapla Group ecosystem.',
    accent: '#2563eb',
  },
  {
    abbr: 'TCA',
    name: 'Công ty CP Nghệ Thuật Tuấn Cường',
    tagline: 'Artwork & Iconic Installations',
    description: 'Chuyên thiết kế và thi công các hạng mục Artwork biểu tượng, điểm nhấn nghệ thuật độc đáo cho các khu nghỉ dưỡng, khu đô thị cao cấp.',
    descriptionEn: 'Specialises in designing and constructing iconic Artwork and unique artistic focal points for resorts and premium urban developments.',
    accent: '#7c3aed',
  },
  {
    abbr: 'BHA',
    name: 'Công ty CP Kiến Trúc BHA',
    tagline: 'Architecture & Landscape Design',
    description: 'Cung cấp dịch vụ thiết kế kiến trúc và cảnh quan, từ concept đến hồ sơ thi công chi tiết, đảm bảo tính thẩm mỹ và công năng cho mọi dự án.',
    descriptionEn: 'Provides architecture and landscape design services, from concept to detailed construction documents, ensuring aesthetics and functionality for every project.',
    accent: '#0891b2',
  },
  {
    abbr: 'TSN',
    name: 'Thaising Nursery (Thailand)',
    tagline: 'Tropical Plant Supply · Thailand',
    description: 'Đối tác vườn ươm chiến lược tại Thái Lan, chuyên cung cấp cây nhiệt đới đặc chủng chất lượng cao phục vụ các dự án cảnh quan cao cấp trong nước.',
    descriptionEn: 'Strategic nursery partner in Thailand, supplying high-quality specialty tropical plants for premium landscape projects across Vietnam.',
    accent: '#15803d',
  },
  {
    abbr: 'GL',
    name: 'Green Light Lighting',
    tagline: 'Landscape & Architectural Lighting',
    description: 'Thiết kế và thi công hệ thống chiếu sáng cảnh quan, chiếu sáng kiến trúc tạo điểm nhấn nghệ thuật về đêm cho các công trình cảnh quan.',
    descriptionEn: 'Designs and installs landscape and architectural lighting systems, creating artistic nighttime highlights for landscape projects.',
    accent: '#ca8a04',
  },
  {
    abbr: 'HD',
    name: 'Công ty XNK Hùng Đạt',
    tagline: 'Landscape Materials & Supply',
    description: 'Nhập khẩu và phân phối vật tư cảnh quan chất lượng cao — đất nền, phân bón, giá thể, đá tự nhiên và vật liệu trang trí sân vườn.',
    descriptionEn: 'Imports and distributes high-quality landscape materials — growing media, fertilizers, substrates, natural stone, and garden decorative materials.',
    accent: '#b45309',
  },
  {
    abbr: 'DLA',
    name: 'Hiệp Hội Cảnh Quan Đà Nẵng',
    tagline: 'Industry Association',
    description: 'Tổ chức hiệp hội ngành cảnh quan tại Đà Nẵng, kết nối các doanh nghiệp, thúc đẩy tiêu chuẩn nghề nghiệp và phát triển nguồn nhân lực ngành.',
    descriptionEn: 'Landscape industry association in Da Nang, connecting businesses, promoting professional standards, and developing industry workforce.',
    accent: '#0f766e',
  },
];

export const newsArticles = [
  {
    slug: 'fam-hoan-thanh-san-golf-laguna-lang-co',
    titleVi: 'Lapla Hoàn Thành Thi Công Cảnh Quan Sân Golf Laguna Lăng Cô',
    titleEn: 'Lapla Completes Landscape Works at Laguna Lang Co Golf Course',
    summaryVi: 'Sau 18 tháng thi công, Lapla đã bàn giao toàn bộ hạng mục cảnh quan và hệ thống tưới tiêu cho dự án sân golf đẳng cấp quốc tế Laguna Lăng Cô tại Thừa Thiên Huế.',
    summaryEn: 'After 18 months of construction, Lapla has handed over all landscape and irrigation works for the world-class Laguna Lang Co Golf Course project in Thua Thien Hue.',
    contentVi: [
      'Dự án sân golf Laguna Lăng Cô là một trong những công trình cảnh quan lớn nhất mà Lapla từng thực hiện. Nằm trong quần thể resort 5 sao Banyan Tree Lăng Cô, sân golf 18 lỗ này đòi hỏi tiêu chuẩn kỹ thuật và thẩm mỹ cực kỳ cao.',
      'Đội ngũ Lapla đã triển khai hơn 45.000 m² thảm cỏ Paspalum Seashore — giống cỏ chuyên dụng chịu mặn cao nhất hiện nay, phù hợp với khí hậu ven biển miền Trung. Song song đó, hệ thống tưới tiêu Rainbird tự động được lắp đặt toàn bộ 18 lỗ với hơn 1.200 đầu phun.',
      'Bên cạnh thảm cỏ, Lapla còn thiết kế và thi công cảnh quan cây xanh bao gồm hơn 3.000 cây nhiệt đới các loại, tạo nên màu sắc đa dạng và bóng mát tự nhiên cho toàn tuyến golf. Các hồ nước nhân tạo cũng được xử lý bờ kè và trồng thủy sinh đảm bảo tính thẩm mỹ lẫn sinh thái.',
      'Phát biểu tại lễ bàn giao, ông Nguyễn Tuấn Cường — Giám đốc Lapla — chia sẻ: "Laguna Lăng Cô là minh chứng rõ ràng nhất cho năng lực của Lapla trong lĩnh vực cảnh quan sân golf quốc tế. Chúng tôi tự hào đã hoàn thành đúng tiến độ và vượt kỳ vọng của chủ đầu tư."',
    ],
    contentEn: [
      'The Laguna Lang Co Golf Course project is one of the largest landscape works Lapla has ever undertaken. Set within the 5-star Banyan Tree Lang Co resort complex, this 18-hole golf course demands exceptionally high technical and aesthetic standards.',
      'The Lapla team installed over 45,000 m² of Paspalum Seashore turf — the most salt-tolerant specialty turf available today, perfectly suited to the Central Vietnam coastal climate. Simultaneously, a fully automated Rainbird irrigation system was installed across all 18 holes with over 1,200 sprinkler heads.',
      'Beyond the turf, Lapla also designed and constructed green landscape planting including over 3,000 tropical trees of various species, creating diverse color and natural shade throughout the golf course. Artificial lakes were also fitted with reinforced banks and aquatic planting to ensure both aesthetic appeal and ecological balance.',
      'Speaking at the handover ceremony, Mr. Nguyen Tuan Cuong — Director of Lapla — shared: "Laguna Lang Co is the clearest testament to Lapla\'s capabilities in international golf course landscaping. We are proud to have completed on schedule and exceeded the investor\'s expectations."',
    ],
    image: 'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671321/kigl4adzgrqyrwdfcg7o.png',
    categoryVi: 'Dự Án',
    categoryEn: 'Projects',
    date: '2025-03-10',
    readTime: 4,
  },
  {
    slug: 'xu-huong-thiet-ke-canh-quan-2025',
    titleVi: 'Xu Hướng Thiết Kế Cảnh Quan Nổi Bật Năm 2025',
    titleEn: 'Top Landscape Design Trends of 2025',
    summaryVi: 'Năm 2025 chứng kiến sự bùng nổ của thiết kế cảnh quan bền vững, kết hợp công nghệ tưới tiêu thông minh và vật liệu tái chế. Lapla chia sẻ những xu hướng đáng chú ý nhất.',
    summaryEn: '2025 sees a boom in sustainable landscape design, blending smart irrigation technology and recycled materials. Lapla shares the most noteworthy trends to watch.',
    contentVi: [
      'Ngành cảnh quan toàn cầu đang trải qua giai đoạn chuyển mình mạnh mẽ. Không còn chỉ chú trọng thẩm mỹ thuần túy, các chủ đầu tư và kiến trúc sư cảnh quan ngày càng hướng đến giải pháp xanh — bền vững, tiết kiệm nước và thân thiện với hệ sinh thái địa phương.',
      'Xu hướng đầu tiên và nổi bật nhất là "Rewilding" — tái hoang dã hóa không gian đô thị. Thay vì trồng cây ngoại lai, các dự án hiện đại ưu tiên loài thực vật bản địa, giảm thiểu bảo dưỡng và tăng đa dạng sinh học. Tại Việt Nam, xu hướng này thể hiện qua việc sử dụng các loài cây nhiệt đới như Cau, Bồ Đề, Bàng lá nhỏ trong không gian đô thị.',
      'Hệ thống tưới tiêu thông minh kết nối IoT là xu hướng thứ hai đang thay đổi cách quản lý cảnh quan. Cảm biến độ ẩm đất, dự báo thời tiết tích hợp và điều khiển từ xa qua ứng dụng di động giúp tiết kiệm đến 40% lượng nước tưới so với phương pháp truyền thống.',
      'Cuối cùng, thiết kế cảnh quan đa chức năng đang trở thành tiêu chuẩn mới: không gian xanh không chỉ đẹp mà còn cần thu hút côn trùng có ích, lọc không khí, quản lý nước mưa và tạo không gian sống cho động vật hoang dã đô thị.',
    ],
    contentEn: [
      'The global landscape industry is undergoing a powerful transformation. No longer focused purely on aesthetics, investors and landscape architects are increasingly turning to green solutions — sustainable, water-efficient and friendly to local ecosystems.',
      'The first and most prominent trend is "Rewilding" — restoring wildness to urban spaces. Rather than planting exotic species, modern projects prioritize native plant species, minimizing maintenance and increasing biodiversity. In Vietnam, this trend manifests through the use of tropical native species such as Areca palms, Ficus, and Small-leaf Terminalia in urban environments.',
      'Smart IoT-connected irrigation systems are the second trend transforming landscape management. Soil moisture sensors, integrated weather forecasting, and remote control via mobile app help save up to 40% of irrigation water compared to traditional methods.',
      'Finally, multi-functional landscape design is becoming the new standard: green spaces must not only be beautiful but also attract beneficial insects, filter air, manage rainwater, and create habitat for urban wildlife.',
    ],
    image: 'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671536/r26fclszliusv87dophg.jpg',
    categoryVi: 'Kiến Thức',
    categoryEn: 'Knowledge',
    date: '2025-02-18',
    readTime: 5,
  },
  {
    slug: 'fam-ky-ket-hop-tac-thaising-nursery',
    titleVi: 'Lapla Ký Kết Hợp Tác Chiến Lược Với Thaising Nursery Thái Lan',
    titleEn: 'Lapla Signs Strategic Partnership With Thailand\'s Thaising Nursery',
    summaryVi: 'Lapla chính thức ký kết hợp đồng hợp tác độc quyền với Thaising Nursery — đơn vị cung cấp cây nhiệt đới hàng đầu Thái Lan, đảm bảo nguồn cây chất lượng cao cho các dự án trong nước.',
    summaryEn: 'Lapla officially signs an exclusive cooperation agreement with Thaising Nursery — Thailand\'s leading tropical plant supplier — securing premium plant stock for domestic projects.',
    contentVi: [
      'Ngày 15 tháng 1 năm 2025, tại văn phòng Lapla tại Đà Nẵng, lễ ký kết hợp tác chiến lược giữa Lapla và Thaising Nursery (Thái Lan) đã chính thức diễn ra. Đây là bước tiến quan trọng trong chiến lược mở rộng chuỗi cung ứng cây cảnh chất lượng cao của Lapla.',
      'Thaising Nursery là một trong những vườn ươm uy tín nhất Đông Nam Á, chuyên cung cấp các loại cây nhiệt đới quý hiếm như Palmera khổng lồ, Cycas, Ficus benjamina cổ thụ và nhiều loài đặc hữu vùng nhiệt đới. Với hơn 30 năm kinh nghiệm, Thaising đã xuất khẩu cây sang hơn 20 quốc gia.',
      'Theo thỏa thuận, Lapla sẽ là đối tác phân phối độc quyền tại miền Trung và Tây Nguyên Việt Nam. Hàng quý, một lô hàng cây đặc chủng sẽ được vận chuyển thẳng từ Thái Lan về các kho bãi của Lapla tại Đà Nẵng.',
      'Giám đốc Lapla cho biết: "Sự hợp tác này giải quyết triệt để vấn đề nguồn cung cây đặc chủng vốn là nút thắt lớn trong các dự án cảnh quan cao cấp. Từ nay, chúng tôi có thể cam kết chủng loại và chất lượng cây với chủ đầu tư ngay từ giai đoạn thiết kế."',
    ],
    contentEn: [
      'On January 15, 2025, at Lapla\'s office in Da Nang, the strategic cooperation signing ceremony between Lapla and Thaising Nursery (Thailand) officially took place. This marks an important step in Lapla\'s strategy to expand its premium ornamental plant supply chain.',
      'Thaising Nursery is one of the most reputable nurseries in Southeast Asia, specializing in rare tropical plants such as giant Palmera, Cycas, ancient Ficus benjamina and many endemic tropical species. With over 30 years of experience, Thaising has exported plants to more than 20 countries.',
      'Under the agreement, Lapla will be the exclusive distribution partner in Central Vietnam and the Central Highlands. Each quarter, a shipment of specialty plants will be transported directly from Thailand to Lapla\'s warehouses in Da Nang.',
      'Lapla\'s director stated: "This partnership definitively resolves the specialty plant supply issue that has been a major bottleneck in premium landscape projects. From now on, we can guarantee plant species and quality to investors from the design stage."',
    ],
    image: 'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671538/sh2jvuvx9kyyuuif8fcl.jpg',
    categoryVi: 'Tin Công Ty',
    categoryEn: 'Company News',
    date: '2025-01-20',
    readTime: 3,
  },
  {
    slug: 'ky-thuat-trong-co-san-golf-chuyen-nghiep',
    titleVi: 'Kỹ Thuật Trồng Và Chăm Sóc Cỏ Sân Golf Chuyên Nghiệp',
    titleEn: 'Professional Golf Course Turf Installation & Maintenance Techniques',
    summaryVi: 'Cỏ sân golf không chỉ là nền tảng của trải nghiệm chơi golf mà còn là thách thức kỹ thuật lớn nhất trong cảnh quan thể thao. Lapla chia sẻ quy trình và bí quyết từ 17 năm kinh nghiệm.',
    summaryEn: 'Golf course turf is not only the foundation of the golfing experience but also the greatest technical challenge in sports landscaping. Lapla shares processes and insights from 17 years of experience.',
    contentVi: [
      'Trong tất cả các hạng mục cảnh quan, cỏ sân golf đòi hỏi kỹ thuật và sự chăm chút cao nhất. Không giống cỏ thông thường, mỗi vị trí trên sân golf — từ tee box, fairway đến green — yêu cầu loại cỏ và thông số kỹ thuật khác nhau.',
      'Tại Lapla, quy trình trồng cỏ sân golf bắt đầu từ khâu phân tích đất: pH, độ thoát nước, thành phần khoáng chất và vi sinh vật trong đất đều được kiểm tra kỹ trước khi lựa chọn giống cỏ. Đối với sân golf ven biển, Paspalum Seashore là lựa chọn tối ưu nhờ khả năng chịu mặn vượt trội. Với sân golf vùng núi hoặc nội địa, Bermuda 419 hoặc Zoysia Matrella được ưu tiên.',
      'Hệ thống tưới tiêu đóng vai trò sống còn trong duy trì chất lượng cỏ. Lapla sử dụng hệ thống Rainbird tự động với cảm biến ET (Evapotranspiration) để tính toán lượng nước tưới chính xác theo từng ngày, giảm lãng phí và đảm bảo cỏ luôn trong trạng thái tốt nhất.',
      'Bảo dưỡng định kỳ bao gồm: cắt cỏ greens hàng ngày ở chiều cao 3–4mm, aerification (đục lỗ thông khí) 2 lần/năm, top-dressing cát và bón phân theo lịch sinh trưởng của cỏ. Đây là những công việc đòi hỏi máy móc chuyên dụng và đội ngũ được đào tạo bài bản.',
    ],
    contentEn: [
      'Of all landscape elements, golf course turf demands the highest level of technical skill and attention. Unlike ordinary grass, each position on a golf course — from tee box, fairway to green — requires different grass species and technical specifications.',
      'At Lapla, the golf turf installation process begins with soil analysis: pH, drainage, mineral composition and soil microorganisms are all carefully tested before selecting the grass variety. For coastal golf courses, Paspalum Seashore is the optimal choice due to its superior salt tolerance. For mountain or inland golf courses, Bermuda 419 or Zoysia Matrella are preferred.',
      'The irrigation system plays a vital role in maintaining turf quality. Lapla uses automated Rainbird systems with ET (Evapotranspiration) sensors to calculate precise daily irrigation amounts, reducing waste and ensuring turf is always in peak condition.',
      'Regular maintenance includes: daily green mowing at 3–4mm height, aerification (aeration) twice per year, sand top-dressing and fertilization according to the turf growth schedule. These tasks require specialized equipment and a professionally trained team.',
    ],
    image: 'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671334/woa4p1d1zugjvfhtxpfo.png',
    categoryVi: 'Kiến Thức',
    categoryEn: 'Knowledge',
    date: '2024-12-05',
    readTime: 6,
  },
  {
    slug: 'hoi-thao-canh-quan-nhiet-doi-da-nang-2024',
    titleVi: 'Lapla Đồng Tổ Chức Hội Thảo Cảnh Quan Nhiệt Đới Tại Đà Nẵng',
    titleEn: 'Lapla Co-Hosts Tropical Landscape Symposium in Da Nang',
    summaryVi: 'Hội thảo chuyên ngành "Cảnh Quan Nhiệt Đới Bền Vững" quy tụ hơn 200 kiến trúc sư, kỹ sư và nhà thầu từ 8 quốc gia, với Lapla là đơn vị đồng tổ chức chính.',
    summaryEn: 'The "Sustainable Tropical Landscape" industry symposium brought together over 200 architects, engineers and contractors from 8 countries, with Lapla as the main co-organizer.',
    contentVi: [
      'Ngày 20–21 tháng 11 năm 2024, Hội thảo Quốc tế Cảnh Quan Nhiệt Đới Bền Vững lần thứ 3 đã diễn ra tại Trung tâm Hội nghị TP. Đà Nẵng. Với sự tham gia của hơn 200 chuyên gia đến từ Việt Nam, Thái Lan, Singapore, Malaysia, Indonesia, Philippines, Nhật Bản và Hàn Quốc, đây là sự kiện ngành cảnh quan lớn nhất khu vực miền Trung từ trước đến nay.',
      'Lapla đảm nhận vai trò đồng tổ chức và chịu trách nhiệm về hạng mục triển lãm thực vật. Gian hàng của Lapla trưng bày hơn 80 loài cây nhiệt đới đặc sắc, trong đó có nhiều loài nhập khẩu từ đối tác Thaising Nursery Thái Lan.',
      'Các chủ đề nổi bật tại hội thảo bao gồm: quản lý nước trong cảnh quan đô thị nhiệt đới, ứng dụng công nghệ số trong thiết kế cảnh quan, và tiêu chuẩn xanh LEED/SITES cho các dự án cảnh quan quy mô lớn. Đặc biệt, báo cáo của Lapla về kinh nghiệm thi công sân golf vùng ven biển nhận được sự quan tâm lớn từ các đại biểu quốc tế.',
      'Hội thảo kết thúc với việc ký kết biên bản ghi nhớ hợp tác giữa Hiệp hội Cảnh quan Đà Nẵng (do Lapla là thành viên sáng lập) và 4 hiệp hội cảnh quan quốc tế, mở ra nhiều cơ hội trao đổi chuyên gia và chuyển giao công nghệ trong tương lai.',
    ],
    contentEn: [
      'On November 20–21, 2024, the 3rd International Sustainable Tropical Landscape Symposium was held at the Da Nang Convention Center. With the participation of over 200 experts from Vietnam, Thailand, Singapore, Malaysia, Indonesia, Philippines, Japan and South Korea, this was the largest landscape industry event in Central Vietnam to date.',
      'Lapla took on the role of co-organizer and was responsible for the botanical exhibition component. Lapla\'s booth showcased over 80 spectacular tropical plant species, including many imported from partner Thaising Nursery in Thailand.',
      'Key topics at the symposium included: water management in tropical urban landscapes, application of digital technology in landscape design, and LEED/SITES green standards for large-scale landscape projects. Notably, Lapla\'s report on golf course construction experience in coastal areas received significant interest from international delegates.',
      'The symposium concluded with the signing of memoranda of understanding between the Da Nang Landscape Association (of which Lapla is a founding member) and 4 international landscape associations, opening up many opportunities for expert exchange and technology transfer in the future.',
    ],
    image: 'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671447/dq8l14ajn2y7kxdku0nb.png',
    categoryVi: 'Sự Kiện',
    categoryEn: 'Events',
    date: '2024-11-22',
    readTime: 4,
  },
  {
    slug: 'canh-quan-khu-do-thi-ben-vung',
    titleVi: 'Thiết Kế Cảnh Quan Khu Đô Thị Bền Vững: Kinh Nghiệm Từ Lapla',
    titleEn: 'Sustainable Urban Landscape Design: Lessons From Lapla',
    summaryVi: 'Khi đô thị hóa tăng tốc, cảnh quan xanh không còn là điểm nhấn thẩm mỹ mà trở thành hạ tầng sinh thái thiết yếu. Lapla chia sẻ bài học từ các dự án khu đô thị lớn tại miền Trung.',
    summaryEn: 'As urbanization accelerates, green landscapes are no longer aesthetic accents but essential ecological infrastructure. Lapla shares lessons from major urban development projects in Central Vietnam.',
    contentVi: [
      'Tốc độ đô thị hóa nhanh chóng tại các thành phố Việt Nam, đặc biệt là Đà Nẵng và các đô thị ven biển miền Trung, đang tạo áp lực lớn lên hệ sinh thái đô thị. Nhiệt độ bề mặt tăng, ngập úng đô thị và ô nhiễm không khí là những vấn đề cấp bách cần giải pháp cảnh quan tổng thể.',
      'Trong 5 năm qua, Lapla đã tham gia thi công cảnh quan cho hơn 15 khu đô thị tại miền Trung, từ các khu biệt thự ven biển đến đô thị tích hợp quy mô lớn. Bài học lớn nhất chúng tôi rút ra là: cảnh quan phải được tích hợp từ giai đoạn quy hoạch tổng mặt bằng, không phải bổ sung sau khi xây dựng xong.',
      'Giải pháp thoát nước mưa tự nhiên (SUDS — Sustainable Urban Drainage Systems) kết hợp với cảnh quan là một trong những tiếp cận hiệu quả nhất. Thay vì dẫn nước mưa vào hệ thống cống ngầm, chúng tôi thiết kế các bioswale (kênh sinh thái), rain garden (vườn thu nước mưa) và vùng đất ngập nước nhân tạo để lọc và tái sử dụng nước tại chỗ.',
      'Kết quả đo lường sau 2 năm tại dự án Khu đô thị Hòa Xuân (Đà Nẵng) cho thấy: nhiệt độ bề mặt trong khu vực có cảnh quan xanh thấp hơn khu không có cây xanh tới 4–6°C vào mùa hè, lượng nước mưa thoát chậm giảm nguy cơ ngập úng xuống 35%, và chỉ số hài lòng của cư dân về môi trường sống tăng đáng kể.',
    ],
    contentEn: [
      'The rapid pace of urbanization in Vietnamese cities, particularly Da Nang and Central Vietnam coastal cities, is placing enormous pressure on urban ecosystems. Rising surface temperatures, urban flooding and air pollution are urgent issues requiring comprehensive landscape solutions.',
      'Over the past 5 years, Lapla has participated in landscape construction for over 15 urban developments in Central Vietnam, from beachside villa estates to large-scale integrated urban areas. The biggest lesson we have learned is: landscaping must be integrated from the master planning stage, not added as an afterthought after construction is complete.',
      'Natural rainwater management (SUDS — Sustainable Urban Drainage Systems) combined with landscaping is one of the most effective approaches. Instead of directing rainwater into underground drainage systems, we design bioswales, rain gardens and artificial wetlands to filter and reuse water on-site.',
      'Measurements taken after 2 years at the Hoa Xuan Urban Area project (Da Nang) show: surface temperatures in landscaped areas are 4–6°C lower than non-landscaped areas in summer, slow-draining rainwater reduces flooding risk by 35%, and the resident satisfaction index for living environment has increased significantly.',
    ],
    image: 'https://res.cloudinary.com/dg9khx2s7/image/upload/v1780671533/jx0ic3w3sdaodjkbwfii.jpg',
    categoryVi: 'Kiến Thức',
    categoryEn: 'Knowledge',
    date: '2024-10-14',
    readTime: 5,
  },
];
